spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console: true
    path: /h2-console

  datasource:
    url: jdbc:h2:mem:todolist
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update


#  logging:
#    file.name: logs/logs-todo-list-application.log
#   pattern:
#      console: "%d{yyyy-mm-dd HH:mm}  %5level --- [ %logger{40} ] : %msg%n"
#    level:
#      #root: INFO
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type: TRACE

